import type { Product, Category } from './types'

export const products: Product[] = [
  // DOG FEEDING
  {
    id: 'elevated-feeder-m',
    name: 'Elevated Dog Feeder M',
    slug: 'elevated-dog-feeder-m',
    category: 'dog-feeding',
    subcategory: 'elevated-feeders',
    price: 34.99,
    description:
      'Give your small dog the comfort they deserve with our elevated feeding station. Designed to reduce neck and joint strain during meals, this raised feeder is crafted from durable bamboo with stainless steel bowls. Perfect for dogs up to 10 kg.',
    shortDescription: 'Raised feeding station with 2× 0.5L stainless steel bowls for small dogs.',
    features: [
      'Ergonomic elevated design reduces neck strain',
      '2× stainless steel 0.5L bowls included',
      'Sustainable bamboo frame',
      'Non-slip rubber feet',
      'Easy to clean — bowls are dishwasher safe',
      'Ideal for dogs up to 10 kg',
    ],
    specs: { Size: 'Medium', Capacity: '2× 0.5L', Material: 'Bamboo + Stainless Steel', 'Suitable for': 'Small dogs' },
    image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.7,
    reviewCount: 124,
    inStock: true,
  },
  {
    id: 'elevated-feeder-l',
    name: 'Elevated Dog Feeder L',
    slug: 'elevated-dog-feeder-l',
    category: 'dog-feeding',
    subcategory: 'elevated-feeders',
    price: 39.99,
    description:
      'Our medium-large elevated feeder is the perfect mealtime upgrade for dogs from 10 to 25 kg. The bamboo stand raises bowls to a comfortable height, supporting better digestion and reducing the risk of bloating.',
    shortDescription: 'Raised feeding station with 2× 1L stainless steel bowls for medium dogs.',
    features: [
      'Ergonomic elevated design reduces neck strain',
      '2× stainless steel 1L bowls included',
      'Sustainable bamboo frame',
      'Non-slip rubber feet',
      'Easy to clean — bowls are dishwasher safe',
      'Ideal for dogs 10–25 kg',
    ],
    specs: { Size: 'Large', Capacity: '2× 1L', Material: 'Bamboo + Stainless Steel', 'Suitable for': 'Medium dogs' },
    image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
  },
  {
    id: 'elevated-feeder-xl',
    name: 'Elevated Dog Feeder XL',
    slug: 'elevated-dog-feeder-xl',
    category: 'dog-feeding',
    subcategory: 'elevated-feeders',
    price: 44.99,
    description:
      'Designed for large and giant breeds, this XL elevated feeder brings meals up to a comfortable height. The wide bamboo base offers exceptional stability, while the two large 2L stainless steel bowls handle even the heartiest appetites.',
    shortDescription: 'Raised feeding station with 2× 2L stainless steel bowls for large dogs.',
    features: [
      'Extra-tall design for large breeds',
      '2× stainless steel 2L bowls included',
      'Extra-wide sustainable bamboo frame for stability',
      'Non-slip rubber feet',
      'Easy to clean — bowls are dishwasher safe',
      'Ideal for dogs over 25 kg',
    ],
    specs: { Size: 'XL', Capacity: '2× 2L', Material: 'Bamboo + Stainless Steel', 'Suitable for': 'Large dogs' },
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'new',
    rating: 4.6,
    reviewCount: 47,
    inStock: true,
  },
  {
    id: 'mango-bowl-05l',
    name: 'Mango Wood Dog Bowl 0.5L',
    slug: 'mango-wood-dog-bowl-05l',
    category: 'dog-feeding',
    subcategory: 'wooden-bowls',
    price: 19.99,
    description:
      'Bring natural warmth to your dog\'s feeding routine with our handcrafted mango wood bowl. Each bowl is unique, with natural grain variations that make it one-of-a-kind. The stainless steel insert is removable and dishwasher safe.',
    shortDescription: 'Handcrafted mango wood bowl with removable 0.5L steel insert.',
    features: [
      'Handcrafted from sustainable mango wood',
      'Each piece has a unique natural grain pattern',
      'Removable 0.5L stainless steel insert',
      'Food-safe finishing',
      'Rubber base prevents sliding',
    ],
    specs: { Capacity: '0.5L', Material: 'Mango Wood + Stainless Steel', Finish: 'Food-safe oil' },
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'mango-bowl-1l',
    name: 'Mango Wood Dog Bowl 1L',
    slug: 'mango-wood-dog-bowl-1l',
    category: 'dog-feeding',
    subcategory: 'wooden-bowls',
    price: 22.99,
    description:
      'Our 1L mango wood bowl is the perfect size for medium to large dogs. Sustainably sourced mango wood meets a generous stainless steel insert — beautiful on a kitchen floor and practical for daily use.',
    shortDescription: 'Handcrafted mango wood bowl with removable 1L steel insert.',
    features: [
      'Handcrafted from sustainable mango wood',
      'Each piece has a unique natural grain pattern',
      'Removable 1L stainless steel insert',
      'Food-safe finishing',
      'Rubber base prevents sliding',
    ],
    specs: { Capacity: '1L', Material: 'Mango Wood + Stainless Steel', Finish: 'Food-safe oil' },
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
  },
  {
    id: 'mango-bowl-2l',
    name: 'Mango Wood Dog Bowl 2L',
    slug: 'mango-wood-dog-bowl-2l',
    category: 'dog-feeding',
    subcategory: 'wooden-bowls',
    price: 26.99,
    description:
      'For big appetites and big personalities. Our 2L mango wood bowl makes a stunning statement in any home while meeting the feeding needs of large and giant breeds.',
    shortDescription: 'Handcrafted mango wood bowl with removable 2L steel insert.',
    features: [
      'Handcrafted from sustainable mango wood',
      'Each piece has a unique natural grain pattern',
      'Removable 2L stainless steel insert',
      'Food-safe finishing',
      'Wide rubber base for extra stability',
    ],
    specs: { Capacity: '2L', Material: 'Mango Wood + Stainless Steel', Finish: 'Food-safe oil' },
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.7,
    reviewCount: 92,
    inStock: true,
  },
  {
    id: 'double-metal-feeder-s',
    name: 'Double Metal Dog Feeder Small',
    slug: 'double-metal-dog-feeder-small',
    category: 'dog-feeding',
    subcategory: 'metal-feeders',
    price: 24.99,
    description:
      'A sleek, minimalist double feeder for small dogs. The powder-coated steel frame holds two stainless steel bowls side by side — one for food, one for water. Clean lines that look at home in modern interiors.',
    shortDescription: 'Minimalist double steel feeder with 2× stainless steel bowls, small size.',
    features: [
      'Powder-coated steel frame in matte black',
      '2× removable stainless steel bowls',
      'Non-slip feet',
      'Dishwasher-safe bowls',
      'Compact footprint for small spaces',
    ],
    specs: { Size: 'Small', Material: 'Powder-coated Steel + Stainless Steel', Color: 'Matte Black' },
    image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
  },
  {
    id: 'double-metal-feeder-l',
    name: 'Double Metal Dog Feeder Large',
    slug: 'double-metal-dog-feeder-large',
    category: 'dog-feeding',
    subcategory: 'metal-feeders',
    price: 29.99,
    description:
      'The large version of our bestselling double metal feeder — made for medium to large breeds. Wider bowls, sturdier frame, same clean aesthetic.',
    shortDescription: 'Minimalist double steel feeder with 2× stainless steel bowls, large size.',
    features: [
      'Heavy-gauge powder-coated steel frame in matte black',
      '2× removable large stainless steel bowls',
      'Wide non-slip rubber feet for stability',
      'Dishwasher-safe bowls',
    ],
    specs: { Size: 'Large', Material: 'Powder-coated Steel + Stainless Steel', Color: 'Matte Black' },
    image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.6,
    reviewCount: 54,
    inStock: true,
  },

  // CAT FEEDING
  {
    id: 'cat-feeder-mango',
    name: 'Double Mango Wood Cat Feeder',
    slug: 'double-mango-wood-cat-feeder',
    category: 'cat-feeding',
    price: 24.99,
    description:
      'A cat feeding station that blends beautifully into your home. Two 0.3L stainless steel bowls sit inside a handcrafted mango wood tray — perfect for food and fresh water side by side.',
    shortDescription: 'Handcrafted mango wood double feeding station with 2× 0.3L stainless steel bowls.',
    features: [
      'Handcrafted mango wood tray',
      '2× removable 0.3L stainless steel bowls',
      'Slightly raised rim prevents food from scattering',
      'Food-safe oil finish',
      'Easy to clean',
    ],
    specs: { Capacity: '2× 0.3L', Material: 'Mango Wood + Stainless Steel' },
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
  },
  {
    id: 'cat-feeder-metal',
    name: 'Double Metal Cat Feeder',
    slug: 'double-metal-cat-feeder',
    category: 'cat-feeding',
    price: 21.99,
    description:
      'A modern minimalist feeding station for cats. The sleek powder-coated frame keeps two stainless steel bowls at a comfortable height, reducing strain on your cat\'s neck and whiskers.',
    shortDescription: 'Minimalist double steel cat feeding station with 2× stainless steel bowls.',
    features: [
      'Powder-coated steel frame in matte black',
      '2× removable stainless steel bowls',
      'Whisker-friendly wide bowl shape',
      'Non-slip feet',
      'Dishwasher-safe bowls',
    ],
    specs: { Material: 'Powder-coated Steel + Stainless Steel', Color: 'Matte Black' },
    image: 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
  },

  // DOG BEDS
  {
    id: 'sambo-dog-bed',
    name: 'Sambo Dog Bed',
    slug: 'sambo-dog-bed',
    category: 'dog-beds',
    price: 59.99,
    description:
      'The Sambo is our signature dog bed — a cushioned, structured sleeping space that looks as good as it feels. Available in multiple earth-tone colors to complement any interior. The removable cover is machine washable.',
    shortDescription: 'Premium structured dog bed with removable machine-washable cover. Multiple colors.',
    features: [
      'High-density memory foam base',
      'Removable, machine-washable cover',
      'Raised bolster edges for a sense of security',
      'Available in Sand, Sage, Stone, and Charcoal',
      'Non-slip base',
      'Suitable for small to large breeds',
    ],
    specs: { Material: 'Memory foam + Fleece cover', 'Care': 'Machine wash cover at 30°C' },
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    variants: [
      { id: 'sambo-sand', label: 'Sand', value: 'sand' },
      { id: 'sambo-sage', label: 'Sage', value: 'sage' },
      { id: 'sambo-stone', label: 'Stone', value: 'stone' },
      { id: 'sambo-charcoal', label: 'Charcoal', value: 'charcoal' },
    ],
  },
  {
    id: 'donut-bed-80',
    name: 'Plush Donut Dog Bed 80 cm',
    slug: 'plush-donut-dog-bed-80cm',
    category: 'dog-beds',
    price: 49.99,
    description:
      'The ultra-soft donut bed your dog will never want to leave. The deep-dish design and plush faux-fur material provide warmth and security — ideal for dogs that love to curl up. The 80 cm size is perfect for small to medium breeds.',
    shortDescription: 'Ultra-soft plush donut bed, 80 cm diameter. Ideal for small to medium dogs.',
    features: [
      'Ultra-soft faux-fur plush material',
      'Deep-dish design encourages natural curling',
      'Self-warming — traps body heat',
      'Removable, machine-washable cover',
      '80 cm diameter',
    ],
    specs: { Diameter: '80 cm', Material: 'Faux fur + PP cotton filling', 'Suitable for': 'Dogs up to 15 kg' },
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
  },
  {
    id: 'donut-bed-90',
    name: 'Plush Donut Dog Bed 90 cm',
    slug: 'plush-donut-dog-bed-90cm',
    category: 'dog-beds',
    price: 59.99,
    description:
      'Same ultra-soft donut design, in a larger 90 cm size. Perfect for medium to large breeds who love the security of a deep-dish bed. The plush faux-fur material is irresistibly soft and self-warming.',
    shortDescription: 'Ultra-soft plush donut bed, 90 cm diameter. Ideal for medium to large dogs.',
    features: [
      'Ultra-soft faux-fur plush material',
      'Deep-dish design encourages natural curling',
      'Self-warming — traps body heat',
      'Removable, machine-washable cover',
      '90 cm diameter',
    ],
    specs: { Diameter: '90 cm', Material: 'Faux fur + PP cotton filling', 'Suitable for': 'Dogs 15–30 kg' },
    image: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 198,
    inStock: true,
  },
  {
    id: 'lounge-bed-110',
    name: 'Lounge Dog Bed 110 cm',
    slug: 'lounge-dog-bed-110cm',
    category: 'dog-beds',
    price: 79.99,
    description:
      'Designed for dogs who like to sprawl out, the Lounge Bed offers a generous 110 cm sleeping surface with a low bolster surround. The linen-look cover adds a premium touch to any living room.',
    shortDescription: 'Spacious 110 cm lounge bed with low bolsters and premium linen-look cover.',
    features: [
      'Generous 110 cm × 90 cm sleeping surface',
      'Supportive foam base with low bolster surround',
      'Premium linen-look removable cover',
      'Machine washable cover',
      'Non-slip base',
      'Ideal for large breeds',
    ],
    specs: { Size: '110 × 90 cm', Material: 'Foam base + Linen-look cover', 'Suitable for': 'Dogs over 25 kg' },
    image: 'https://images.unsplash.com/photo-1559715745-e1b33a271c8f?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'new',
    rating: 4.7,
    reviewCount: 83,
    inStock: true,
  },

  // DOG TRAVEL
  {
    id: 'car-seat-cover',
    name: 'Waterproof Car Seat Cover',
    slug: 'waterproof-car-seat-cover',
    category: 'dog-travel',
    price: 44.99,
    description:
      'Keep your car interior clean and your dog secure. Our heavy-duty waterproof seat cover protects against mud, fur, and scratches while creating a comfortable hammock-style space for your dog in the back seat.',
    shortDescription: 'Heavy-duty waterproof hammock-style car seat cover with side protection.',
    features: [
      '100% waterproof Oxford fabric',
      'Hammock-style with adjustable straps',
      'Side flap protection for door panels',
      'Mesh window for dog visibility',
      'Fits most standard car back seats',
      'Machine washable',
    ],
    specs: { Material: '600D Oxford fabric', 'Fits': 'Standard back seats', Waterproof: 'Yes' },
    image: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
  },
  {
    id: 'dog-harness',
    name: 'Dog Harness',
    slug: 'dog-harness',
    category: 'dog-travel',
    price: 29.99,
    description:
      'A comfortable, escape-proof harness for everyday walks and car travel. The padded chest plate distributes pressure evenly, while the sturdy D-ring provides a secure attachment point.',
    shortDescription: 'Padded escape-proof harness for walks and car travel. Multiple sizes.',
    features: [
      'Padded chest plate for comfort',
      'Escape-proof secure buckle system',
      'Front and back D-ring attachment points',
      'Reflective stitching for visibility',
      'Adjustable straps for perfect fit',
    ],
    specs: { Material: 'Nylon + Neoprene padding', Attachment: 'Front and back D-rings', Reflective: 'Yes' },
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    variants: [
      { id: 'harness-xs', label: 'XS', value: 'xs' },
      { id: 'harness-s', label: 'S', value: 's' },
      { id: 'harness-m', label: 'M', value: 'm' },
      { id: 'harness-l', label: 'L', value: 'l' },
      { id: 'harness-xl', label: 'XL', value: 'xl' },
    ],
  },
  {
    id: 'travel-water-bottle',
    name: 'Travel Water Bottle',
    slug: 'travel-water-bottle',
    category: 'dog-travel',
    price: 17.99,
    description:
      'Never let your dog go thirsty on the go. Our one-handed travel bottle features a flip-out drinking trough — just squeeze to fill, let your dog drink, then flip it back to return unused water to the bottle.',
    shortDescription: 'One-handed travel water bottle with fold-out drinking trough. 750ml.',
    features: [
      '750ml BPA-free Tritan bottle',
      'Fold-out drinking trough',
      'One-handed operation — squeeze to fill',
      'Leak-proof cap',
      'Lightweight at just 180g',
      'Carabiner clip for bag attachment',
    ],
    specs: { Capacity: '750ml', Material: 'BPA-free Tritan + Food-grade silicone', Weight: '180g' },
    image: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.8,
    reviewCount: 221,
    inStock: true,
    badge: 'bestseller',
  },
  {
    id: 'collapsible-travel-bowl',
    name: 'Collapsible Travel Bowl',
    slug: 'collapsible-travel-bowl',
    category: 'dog-travel',
    price: 9.99,
    description:
      'The ultimate lightweight travel bowl — fold flat to pocket size, pop open for a full-size meal or water bowl. Food-grade silicone stands up to outdoor use.',
    shortDescription: 'Foldable food-grade silicone bowl for food and water on the go.',
    features: [
      'Food-grade silicone — safe for food and water',
      'Folds flat to just 2 cm',
      '600ml capacity when open',
      'Carabiner clip included',
      'Dishwasher safe',
      'Lightweight at just 90g',
    ],
    specs: { Capacity: '600ml', Material: 'Food-grade silicone', 'Folded height': '2 cm' },
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.5,
    reviewCount: 134,
    inStock: true,
  },

  // DOG OUTDOOR
  {
    id: 'dog-pool-80',
    name: 'Foldable Dog Pool 80 cm',
    slug: 'foldable-dog-pool-80cm',
    category: 'dog-outdoor',
    price: 24.99,
    description:
      'Keep small dogs cool all summer long. This compact foldable pool sets up in seconds without tools and folds flat for easy storage. The puncture-resistant PVC base holds up to energetic splashing.',
    shortDescription: 'Compact foldable summer pool, 80 cm diameter. No inflation needed.',
    features: [
      'No inflation needed — unfold and fill',
      '80 cm diameter, 25 cm depth',
      'Puncture-resistant PVC',
      'Non-slip textured base',
      'Drain hole for easy emptying',
      'Folds flat for compact storage',
    ],
    specs: { Diameter: '80 cm', Depth: '25 cm', Material: 'Heavy-duty PVC', 'Suitable for': 'Small dogs' },
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
  },
  {
    id: 'dog-pool-120',
    name: 'Foldable Dog Pool 120 cm',
    slug: 'foldable-dog-pool-120cm',
    category: 'dog-outdoor',
    price: 32.99,
    description:
      'The perfect summer investment for medium dogs. The 120 cm pool gives your dog room to cool off and splash around. No pump needed — just unfold, fill, and enjoy.',
    shortDescription: 'Foldable summer pool, 120 cm diameter. Perfect for medium dogs.',
    features: [
      'No inflation needed — unfold and fill',
      '120 cm diameter, 30 cm depth',
      'Puncture-resistant heavy-duty PVC',
      'Non-slip textured base',
      'Drain hole for easy emptying',
      'Folds flat for compact storage',
    ],
    specs: { Diameter: '120 cm', Depth: '30 cm', Material: 'Heavy-duty PVC', 'Suitable for': 'Medium dogs' },
    image: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
  },
  {
    id: 'dog-pool-160',
    name: 'Foldable Dog Pool 160 cm',
    slug: 'foldable-dog-pool-160cm',
    category: 'dog-outdoor',
    price: 44.99,
    description:
      'Give large breeds the summer splash zone they deserve. At 160 cm wide, this pool offers real room to cool down on hot days. Built from extra-thick PVC that stands up to large, active dogs.',
    shortDescription: 'Large foldable summer pool, 160 cm diameter. Perfect for large dogs.',
    features: [
      'No inflation needed — unfold and fill',
      '160 cm diameter, 35 cm depth',
      'Extra-thick puncture-resistant PVC',
      'Non-slip textured base',
      'Large drain hole for fast emptying',
      'Folds flat for compact storage',
    ],
    specs: { Diameter: '160 cm', Depth: '35 cm', Material: 'Extra-thick PVC', 'Suitable for': 'Large dogs' },
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=600&q=80',
    bolUrl: 'https://www.bol.com',
    badge: 'new',
    rating: 4.7,
    reviewCount: 72,
    inStock: true,
  },
]

export const categories: Category[] = [
  {
    id: 'dog-feeding',
    name: 'Dog Bowls',
    slug: 'dog-bowls',
    description: 'Elevated feeders, mango wood bowls, and double metal feeders for dogs of every size.',
    image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=800&q=80',
  },
  {
    id: 'cat-feeding',
    name: 'Cat Bowls',
    slug: 'cat-bowls',
    description: 'Beautiful mango wood and metal feeding stations designed with your cat in mind.',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80',
  },
  {
    id: 'dog-beds',
    name: 'Dog Beds',
    slug: 'dog-beds',
    description: 'From plush donut beds to spacious lounge beds — a cozy spot for every dog.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&q=80',
  },
  {
    id: 'dog-travel',
    name: 'Dog Travel',
    slug: 'dog-travel',
    description: 'Everything you need for adventures with your dog — car covers, harnesses, and more.',
    image: 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=800&q=80',
  },
  {
    id: 'dog-outdoor',
    name: 'Dog Pools',
    slug: 'dog-pools',
    description: 'Foldable splash pools to keep your dog cool and happy all summer long.',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80',
  },
]

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.badge === 'bestseller').slice(0, 4)
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug)
}
